name:                haskell-codescreen-fibonacci
version:             1.0.0.0
github:              "Code-Screen/Haskell-CodeScreen-Fibonacci"
author:              "Dave Cervi"
maintainer:          "dave@codescreen.dev"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Code-Screen/Haskell-CodeScreen-Fibonaccii#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-codescreen-fibonacci-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-codescreen-fibonacci

tests:
  haskell-codescreen-fibonacci-test:
    defaults: hspec/hspec@master
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-codescreen-fibonacci
